---
title: "Group 7 proposal"
output: html_document
---


**Group members (names and UNIs)**:  

*   Nancy Fang nf2466  
*   Maggie (Mengyuan) Li ml4424  
*   Rachel Tao rht2112  
*   Linh Tran lmt2203  


**Tentative project title**: Abortion access across the US

**Motivation for this project** 

For this project, we aim to examine sociodemographic that may influence access to abortion in the United States. One study showed that of women who received a nonhospital abortion, 24% traveled at least 50 miles from their home to an abortion facility (Henshaw 1995). We plan to investigate the relationship between transportation time to facility, gestational age, and race on abortion access. We are interested in visualizing these data to hopefully help disseminate this information in a digestible way to inform outreach/education strategies and policy. 

**Intended final products** 

We will build a website that can be used to further public understanding of abortion access in the United States, including visualizations of data from the Guttmacher Institute's 2014 Abortion Patient Survey. For our descriptive statistics presentation, we will to focus on how transportation time to abortion facility differs across states and between different demographic groups. 

**Anticipated data sources** 
We have requested access to the the Guttmacher Institute's 2014 Abortion Patient Survey. This is a public-use database from a nationally representative sample of women obtaining non-hospital abortions in 2014. A total of 8,380 abortion patients provided information about the demographic characteristics of age, race and ethnicity and educational attainment, as well as contraceptive use in the month they became pregnant, health insurance coverage during the time period of the abortion, how they were paying for abortion services, foreign-born status, and how long ago they made the appointment.

**Planned analyses / visualizations / coding challenges** 
We plan to create interactive data visualizations showing:

*   Distribution of transportation time by gestational age (histograms or density ridges plots)
*   How they paid for abortion services and health insurance coverage (scatterplot)
*   Distribution of transportation time by race (boxplot or violin plot)

In addition, we will run linear regression analyses to examine the relationship between transportation time, race, gestational age and other covariates on abortion access.

As a relatively small dataset, we anticipate minimal coding challenges. However, from the provided user guide, we know that certain variables, such as insurance status, were not completed by each participant. Additionally, some participants had multiple insurances but the survey dataset only allowed for the coding of one. This may skew the results that we find. The dataset has also removed zip codes as a identifying variable. While we originally hoped to look at correlation between where a patient lived to variables related to abortion access, this survey will not allow us to do so.

**The planned timeline** 

    + Nov 7th: Submit project proposal
    + Nov 12th: Finalize data sources and start working on questions of interest
    + Nov 12-20th: Work on exploratory analysis (visualization, summaries and statistical analyses), discuss major findings
    + Nov 20-Dec 2nd: Create a webpage and screencast
    + Dec 2-5: Final review 
    + Dec 5th: submit final project
    
**Questions**

*  Relationship between abortion rate and contraceptive funding/ Counties without provider/Hostility by state.

*  Percent of women living in counties without providers vs. hostility ?

*  Percent of teen birth rate and percent of women in need of public funding (need bc under 20).

